### ISSUE TITLE
Does SpriteKit have bright future to make mature 2d game ?

### ISSUE THREAD

**Issue by nvcken** [gskbyte/jotajota#1]
just want to know from your experience.
Hope u can help

**Comment by gskbyte** [comment]
Well, it's hard to say, we've just made this small game, which was our first experience with SpriteKit, and another one which we haven't published yet.

I had worked before with Cocos2D and my feeling was that it was much more powerful and it was also better optimized, but in my opinion SpriteKit is much easier to learn and you will get results faster.

So depending on your case I would choose one or the other. I would go for Cocos2D if I would want to do something advanced and multiplatform, but for a simple iOS game SpriteKit is more than enough.

Best regards

**Comment by nvcken** [comment]
Thanks for help
